/**
 * Block Types - All block IDs and their properties
 */

export type BlockId = 
  | 'air' | 'water' | 'bedrock'
  | 'grass' | 'dirt' | 'stone' | 'sand' | 'snow'
  | 'wood_oak' | 'leaves_oak' | 'wood_pine' | 'leaves_pine'
  | 'coal_ore' | 'copper_ore' | 'iron_ore' | 'gold_ore' | 'diamond_ore'
  | 'crystal_ore' | 'ancient_stone'
  | 'volcanic_rock' | 'ash' | 'lava'
  | 'ice' | 'packed_ice' | 'frozen_grass'
  | 'planks' | 'bricks' | 'glass' | 'torch'
  | 'crafting_table' | 'chest';

export interface BlockData {
  id: BlockId;
  name: string;
  hardness: number; // Time to mine (seconds)
  toolRequired?: string;
  miningSpeed?: Record<string, number>;
  drops: { itemId: string; count: [number, number] }[];
  material: string;
  category: 'natural' | 'building' | 'ore' | 'decoration' | 'fluid' | 'special';
  transparent: boolean;
  collision: boolean;
  lightEmission: number; // 0-15
  color: string;
}

export const BLOCKS: Record<BlockId, BlockData> = {
  air: {
    id: 'air',
    name: 'Air',
    hardness: 0,
    drops: [],
    material: 'air',
    category: 'natural',
    transparent: true,
    collision: false,
    lightEmission: 0,
    color: '#000000',
  },
  water: {
    id: 'water',
    name: 'Water',
    hardness: 0,
    drops: [],
    material: 'water',
    category: 'fluid',
    transparent: true,
    collision: false,
    lightEmission: 0,
    color: '#3399ff',
  },
  bedrock: {
    id: 'bedrock',
    name: 'Bedrock',
    hardness: Infinity,
    drops: [],
    material: 'bedrock',
    category: 'natural',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#2a2a2a',
  },
  grass: {
    id: 'grass',
    name: 'Grass Block',
    hardness: 0.8,
    drops: [{ itemId: 'dirt', count: [1, 1] }],
    material: 'grass',
    category: 'natural',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#5dbb63',
  },
  dirt: {
    id: 'dirt',
    name: 'Dirt',
    hardness: 0.5,
    drops: [{ itemId: 'dirt', count: [1, 1] }],
    material: 'dirt',
    category: 'natural',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#8b5a2b',
  },
  stone: {
    id: 'stone',
    name: 'Stone',
    hardness: 1.5,
    toolRequired: 'pickaxe',
    drops: [{ itemId: 'cobblestone', count: [1, 1] }],
    material: 'stone',
    category: 'natural',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#7a7a7a',
  },
  sand: {
    id: 'sand',
    name: 'Sand',
    hardness: 0.4,
    toolRequired: 'shovel',
    drops: [{ itemId: 'sand', count: [1, 1] }],
    material: 'sand',
    category: 'natural',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#e6d8a3',
  },
  snow: {
    id: 'snow',
    name: 'Snow Block',
    hardness: 0.3,
    toolRequired: 'shovel',
    drops: [{ itemId: 'snowball', count: [1, 4] }],
    material: 'snow',
    category: 'natural',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#fffafa',
  },
  wood_oak: {
    id: 'wood_oak',
    name: 'Oak Log',
    hardness: 2.0,
    toolRequired: 'axe',
    drops: [{ itemId: 'wood_oak', count: [1, 1] }],
    material: 'wood',
    category: 'natural',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#6b4423',
  },
  leaves_oak: {
    id: 'leaves_oak',
    name: 'Oak Leaves',
    hardness: 0.2,
    drops: [
      { itemId: 'stick', count: [1, 3] },
      { itemId: 'apple', count: [0, 1] }],
    material: 'leaves',
    category: 'natural',
    transparent: true,
    collision: true,
    lightEmission: 0,
    color: '#228b22',
  },
  wood_pine: {
    id: 'wood_pine',
    name: 'Pine Log',
    hardness: 2.0,
    toolRequired: 'axe',
    drops: [{ itemId: 'wood_pine', count: [1, 1] }],
    material: 'wood',
    category: 'natural',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#4a3728',
  },
  leaves_pine: {
    id: 'leaves_pine',
    name: 'Pine Leaves',
    hardness: 0.2,
    drops: [{ itemId: 'stick', count: [1, 3] }],
    material: 'leaves',
    category: 'natural',
    transparent: true,
    collision: true,
    lightEmission: 0,
    color: '#1a5c3a',
  },
  coal_ore: {
    id: 'coal_ore',
    name: 'Coal Ore',
    hardness: 3.0,
    toolRequired: 'pickaxe',
    drops: [{ itemId: 'coal', count: [1, 2] }],
    material: 'stone',
    category: 'ore',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#3a3a3a',
  },
  copper_ore: {
    id: 'copper_ore',
    name: 'Copper Ore',
    hardness: 3.5,
    toolRequired: 'pickaxe',
    drops: [{ itemId: 'copper_ingot', count: [1, 2] }],
    material: 'stone',
    category: 'ore',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#d48c4a',
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Iron Ore',
    hardness: 4.0,
    toolRequired: 'pickaxe',
    drops: [{ itemId: 'iron_ore', count: [1, 1] }],
    material: 'stone',
    category: 'ore',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#a67c52',
  },
  gold_ore: {
    id: 'gold_ore',
    name: 'Gold Ore',
    hardness: 4.5,
    toolRequired: 'pickaxe',
    drops: [{ itemId: 'gold_ore', count: [1, 1] }],
    material: 'stone',
    category: 'ore',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#ffd700',
  },
  diamond_ore: {
    id: 'diamond_ore',
    name: 'Diamond Ore',
    hardness: 5.0,
    toolRequired: 'pickaxe',
    drops: [{ itemId: 'diamond', count: [1, 1] }],
    material: 'stone',
    category: 'ore',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#5dade2',
  },
  crystal_ore: {
    id: 'crystal_ore',
    name: 'Celestial Crystal',
    hardness: 6.0,
    toolRequired: 'pickaxe',
    drops: [{ itemId: 'crystal_shard', count: [1, 2] }],
    material: 'crystal',
    category: 'ore',
    transparent: true,
    collision: true,
    lightEmission: 8,
    color: '#c77dff',
  },
  ancient_stone: {
    id: 'ancient_stone',
    name: 'Ancient Stone',
    hardness: 7.0,
    toolRequired: 'pickaxe',
    drops: [{ itemId: 'ancient_fragment', count: [1, 1] }],
    material: 'ancient',
    category: 'ore',
    transparent: false,
    collision: true,
    lightEmission: 4,
    color: '#6a4a8a',
  },
  volcanic_rock: {
    id: 'volcanic_rock',
    name: 'Volcanic Rock',
    hardness: 3.0,
    toolRequired: 'pickaxe',
    drops: [{ itemId: 'volcanic_rock', count: [1, 1] }],
    material: 'stone',
    category: 'natural',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#3a3a3a',
  },
  ash: {
    id: 'ash',
    name: 'Ash Block',
    hardness: 0.6,
    toolRequired: 'shovel',
    drops: [{ itemId: 'ash', count: [1, 1] }],
    material: 'ash',
    category: 'natural',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#8a8a8a',
  },
  lava: {
    id: 'lava',
    name: 'Lava',
    hardness: 0,
    drops: [],
    material: 'lava',
    category: 'fluid',
    transparent: true,
    collision: false,
    lightEmission: 15,
    color: '#ff4500',
  },
  ice: {
    id: 'ice',
    name: 'Ice',
    hardness: 0.4,
    drops: [],
    material: 'ice',
    category: 'natural',
    transparent: true,
    collision: true,
    lightEmission: 0,
    color: '#aaddff',
  },
  packed_ice: {
    id: 'packed_ice',
    name: 'Packed Ice',
    hardness: 0.8,
    drops: [],
    material: 'ice',
    category: 'natural',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#88ccff',
  },
  frozen_grass: {
    id: 'frozen_grass',
    name: 'Frozen Grass',
    hardness: 0.8,
    drops: [{ itemId: 'dirt', count: [1, 1] }],
    material: 'grass',
    category: 'natural',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#6b9b6b',
  },
  planks: {
    id: 'planks',
    name: 'Wood Planks',
    hardness: 1.5,
    toolRequired: 'axe',
    drops: [{ itemId: 'planks', count: [1, 1] }],
    material: 'wood',
    category: 'building',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#a0825a',
  },
  bricks: {
    id: 'bricks',
    name: 'Bricks',
    hardness: 2.0,
    toolRequired: 'pickaxe',
    drops: [{ itemId: 'brick', count: [1, 1] }],
    material: 'brick',
    category: 'building',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#a0522d',
  },
  glass: {
    id: 'glass',
    name: 'Glass',
    hardness: 0.3,
    drops: [],
    material: 'glass',
    category: 'building',
    transparent: true,
    collision: true,
    lightEmission: 0,
    color: '#e0f8ff',
  },
  torch: {
    id: 'torch',
    name: 'Torch',
    hardness: 0,
    drops: [{ itemId: 'torch', count: [1, 1] }],
    material: 'torch',
    category: 'decoration',
    transparent: true,
    collision: false,
    lightEmission: 14,
    color: '#ffa500',
  },
  crafting_table: {
    id: 'crafting_table',
    name: 'Crafting Table',
    hardness: 2.5,
    toolRequired: 'axe',
    drops: [{ itemId: 'crafting_table', count: [1, 1] }],
    material: 'wood',
    category: 'special',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#8b6f47',
  },
  chest: {
    id: 'chest',
    name: 'Chest',
    hardness: 2.5,
    toolRequired: 'axe',
    drops: [{ itemId: 'chest', count: [1, 1] }],
    material: 'wood',
    category: 'special',
    transparent: false,
    collision: true,
    lightEmission: 0,
    color: '#654321',
  },
};

export const ALL_BLOCK_IDS = Object.keys(BLOCKS) as BlockId[];

export function getBlock(id: BlockId): BlockData {
  return BLOCKS[id];
}

export function isTransparent(blockId: BlockId): boolean {
  return BLOCKS[blockId]?.transparent ?? true;
}

export function isSolid(blockId: BlockId): boolean {
  return BLOCKS[blockId]?.collision ?? false;
}

export function getHardness(blockId: BlockId): number {
  return BLOCKS[blockId]?.hardness ?? 1;
}
